apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hello-world-js
  namespace: argocd
spec:
  destination:
    namespace: prod-hello-world-js
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/one-image
    helm:
      releaseName: prod-hello-world-js
      values: |
        host: hello-world-js.k8s.sikademo.com
        image: registry.sikademo.com/tacr/hello-world-js:master-1724f362-2
        containerPort: 3000
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
