apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/prod
    repoURL: https://gitlab.sikademo.com/tacr/argocd-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
